name: Check
on: [ push, pull_request ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: "adopt"
    - name: Check
      run: ./gradlew check
