name: Reftests on Linux
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  reftest-with-libc:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up OpenJDK 8 and 21, with 21 as default
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: |
          8
          21
    - name: Make build/reftestLibc
      run: mkdir -p build/reftestLibc
    - name: Compile try_strftime.c
      run: gcc -o build/reftestLibc/try_strftime src/reftestLibc/resources/try_strftime.c
    - name: Compile try_strptime.c
      run: gcc -o build/reftestLibc/try_strptime src/reftestLibc/resources/try_strptime.c
    - name: Reftest with libc
      run: ./gradlew --info -PreftestLibcTryStrftime=build/reftestLibc/try_strftime -PreftestLibcTryStrptime=build/reftestLibc/try_strptime reftestLibc
